In [319]:
# Database of Used Cars from Kaggle website
## Raw data to be cleaned and analysis conducted from the data

In [320]:
import pandas as pd
import numpy as np

autos = pd.read_csv("autos.csv", encoding = "Latin-1")

In [321]:
autos

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÜV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [322]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
dateCrawled            50000 non-null object
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

In [323]:
autos.head()

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

In [324]:
# Observations
## Dataset has 20 columns
## Some columns have "NAN" values
## Columns should be reformatted to lowercases
## Price column need to be reformatted to exclude the '$' sign
## Odometer column should be reformatted to exclude the 'Km' symbol

In [325]:
autos.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

In [326]:
edited_cols = autos.rename(index = str, columns={'dateCrawled': 'date_crawled', 'name': 'name', 'offerType': 'offer_type', 'price':'price', 'abtest':'abtest', 'vehicleType':'vehicle_type', 'yearOfRegistration':'registration_year', 'gearbox':'gearbox', 'powerPS':'power_p_s','model':'model','odometer':'odometer','monthOfRegistration':'registration_month', 'fuelType':'fuel_type', 'brand':'brand', 'notRepairedDamage':'unrepaired_damage', 'dateCreated':'ad_created','nrOfPictures':'nr_of_pictures','postalCode':'postal_code', 'lastSeen':'last_seen'})
autos = edited_cols
autos.columns

Index(['date_crawled', 'name', 'seller', 'offer_type', 'price', 'abtest',
       'vehicle_type', 'registration_year', 'gearbox', 'power_p_s', 'model',
       'odometer', 'registration_month', 'fuel_type', 'brand',
       'unrepaired_damage', 'ad_created', 'nr_of_pictures', 'postal_code',
       'last_seen'],
      dtype='object')

In [327]:
autos.head()

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_p_s,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

In [328]:
# At this point, all columns in the autos data have been modified in order to make it easier to manipulated values in any column

In [329]:
autos.describe(include = 'all').head(4)

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_p_s,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
count,50000,50000,50000,50000,50000,50000,44905,50000.0,47320,50000.0,47242,50000,50000.0,45518,50000,40171,50000,50000.0,50000.0,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-03-27 22:55:05,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8

In [330]:
# Observations:
## registration_year, power_p_s, nr_of_pictures (should be numeric) is 'NaN'
### Price and odoemeter should be stored as numbers. Signs('$' and 'Km') should be replaced from them

In [331]:
# Focus now is on removing non numeric values from price and odometer columns

In [332]:
autos['price'] = autos['price'].str.replace("$",'').str.replace(",",'').astype(float)
autos['price']

0         5000.0
1         8500.0
2         8990.0
3         4350.0
4         1350.0
5         7900.0
6          300.0
7         1990.0
8          250.0
9          590.0
10         999.0
11         350.0
12        5299.0
13        1350.0
14        3999.0
15       18900.0
16         350.0
17        5500.0
18         300.0
19        4150.0
20        3500.0
21       41500.0
22       25450.0
23        7999.0
24       48500.0
25          90.0
26         777.0
27           0.0
28        5250.0
29        4999.0
          ...
49970    15800.0
49971      950.0
49972     3300.0
49973     6000.0
49974        0.0
49975     9700.0
49976     5900.0
49977     5500.0
49978      900.0
49979    11000.0
49980      400.0
49981     2000.0
49982     1950.0
49983      600.0
49984        0.0
49985     1000.0
49986    15900.0
49987    21990.0
49988     9550.0
49989      150.0
49990    17500.0
49991      500.0
49992     4800.0
49993     1650.0
49994     5000.0
49995    24900.0
49996     1980.0
49997    13200.0
49998    22900.0
49999     1250.0
Name: price, Length: 50000, dtype: float64

In [333]:
autos['odometer'].unique()

array(['150,000km', '70,000km', '50,000km', '80,000km', '10,000km',
       '30,000km', '125,000km', '90,000km', '20,000km', '60,000km',
       '5,000km', '100,000km', '40,000km'], dtype=object)

In [334]:
autos['odometer'] = autos['odometer'].str.replace(",",'').str.replace("km",'').astype(float)
autos['odometer']

0        150000.0
1        150000.0
2         70000.0
3         70000.0
4        150000.0
5        150000.0
6        150000.0
7        150000.0
8        150000.0
9        150000.0
10       150000.0
11       150000.0
12        50000.0
13       150000.0
14       150000.0
15        80000.0
16       150000.0
17       150000.0
18       150000.0
19       150000.0
20       150000.0
21       150000.0
22        10000.0
23       150000.0
24        30000.0
25       150000.0
26       125000.0
27       150000.0
28       150000.0
29       150000.0
           ...
49970     60000.0
49971    150000.0
49972    150000.0
49973    150000.0
49974    150000.0
49975    100000.0
49976    150000.0
49977    150000.0
49978    150000.0
49979     70000.0
49980    125000.0
49981    150000.0
49982     90000.0
49983    150000.0
49984    150000.0
49985    150000.0
49986    125000.0
49987     50000.0
49988    150000.0
49989    150000.0
49990     30000.0
49991    150000.0
49992    125000.0
49993    150000.0
49994    150000.0
49995    100000.0
49996    150000.0
49997      5000.0
49998     40000.0
49999    150000.0
Name: odometer, Length: 50000, dtype: float64

In [335]:
# There is the need to rename the 'odometer and price column

In [336]:
edited_price_odometer_cols = autos.rename(index = str, columns = {'price': 'price_$', 'odometer': 'odometer_km'})
autos = edited_price_odometer_cols
autos.columns

Index(['date_crawled', 'name', 'seller', 'offer_type', 'price_$', 'abtest',
       'vehicle_type', 'registration_year', 'gearbox', 'power_p_s', 'model',
       'odometer_km', 'registration_month', 'fuel_type', 'brand',
       'unrepaired_damage', 'ad_created', 'nr_of_pictures', 'postal_code',
       'last_seen'],
      dtype='object')

In [337]:
autos.head(50)

,date_crawled,name,seller,offer_type,price_$,abtest,vehicle_type,registration_year,gearbox,power_p_s,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,5000.0,control,bus,2004,manuell,158,andere,150000.0,3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,8500.0,control,limousine,1997,automatik,286,7er,150000.0,6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,8990.0,test,limousine,2009,manuell,102,golf,70000.0,7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,4350.0,control,kleinwagen,2007,automatik,71,fortwo,70000.0,6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,1350.0,test,kombi,2003,manuell,0,focus,150000.0,7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,7900.0,test,bus,2006,automatik,150,voyager,150000.0,4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,300.0,test,limousine,1995,manuell,90,golf,150000.0,8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,1990.0,control,limousine,1998,manuell,90,golf,150000.0,12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,250.0,test,NaN,2000,manuell,0,arosa,150000.0,10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,590.0,control,bus,1997,manuell,90,megane,150000.0,7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,999.0,test,NaN,2017,manuell,90,NaN,150000.0,4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,350.0,control,NaN,2000,NaN,0,NaN,150000.0,0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,5299.0,control,kleinwagen,2010,automatik,71,fortwo,50000.0,9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,1350.0,control,limousine,1999,manuell,101,a3,150000.0,11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,3999.0,test,kleinwagen,2007,manuell,75,clio,150000.0,9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,18900.0,test,coupe,1982,automatik,203,NaN,80000.0,6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,350.0,test,kombi,1999,manuell,101,vectra,150000.0,5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,5500.0,test,coupe,1990,manuell,205,scirocco,150000.0,6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,300.0,control,bus,1995,manuell,150,3er,150000.0,0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,4150.0,control,suv,2004,manuell,124,andere,150000.0,2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,3500.0,test,kombi,2003,manuell,131,a4,150000.0,5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,41500.0,test,cabrio,2004,manuell,320,911,150000.0,4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,25450.0,control,cabrio,2015,manuell,184,cooper,10000.0,1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,7999.0,control,bus,2010,manuell,120,NaN,150000.0,2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,48500.0,control,limousine,2014,automatik,306,5er,30000.0,12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,90.0,control,kombi,1996,manuell,116,NaN,150000.0,4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,777.0,control,kleinwagen,1992,manuell,54,polo,125000.0,2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,0.0,control,NaN,2005,NaN,0,NaN,150000.0,0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,5250.0,control,kleinwagen,2007,manuell,110,cooper,150000.0,7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,4999.0,test,kombi,2004,automatik,204,e_klasse,150000.0,10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
30,2016-03-14 11:47:31,Peugeot_206_Unfallfahrzeug,privat,Angebot,80.0,test,kleinwagen,2002,manuell,60,2_reihe,150000.0,6,benzin,peugeot,ja,2016-03-14 00:00:00,0,57076,2016-03-14 11:47:31
31,2016-03-14 16:53:09,Noch_gut_erhaltenen_C_320,privat,Angebot,2850.0,test,kombi,2002,automatik,218,c_klasse,150000.0,7,benzin,mercedes_benz,nein,2016-03-14 00:00:00,0,41065,2016-03-16 07:19:04
32,2016-03-20 05:03:03,Corsa_mit_TÜV_5.2016,privat,Angebot,350.0,control,kleinwagen,1999,manuell,0,corsa,150000.0,7,benzin,opel,NaN,2016-03-20 00:00:00,0,27619,2016-04-06 03:15:20
33,2016-03-15 12:25:26,Audi_A3_2.0_TDI_Sportback_DPF_Kupplung_defekt_...,privat,Angebot,4800.0,test,kombi,2006,manuell,140,a3,150000.0,8,diesel,audi,nein,2016-03-15 00:00:00,0,61169,2016-04-07 13:15:31
34,2016-04-05 07:55:07,Bmw_530d__navi_tuv03/18,privat,Angebot,2600.0,test,kombi,2000,automatik,193,5er,150000.0,6,diesel,bmw,NaN,2016-04-05 00:00:00,0,95111,2016-04-07 12:15:47
35,2016-03-29 21:52:56,Ford_Mondeo,privat,Angebot,1200.0,test,kombi,1998,manuell,0,mondeo,150000.0,12,benzin,ford,nein,2016-03-29 00:00:00,0,52428,2016-04-06 08:45:35
36,2016-03-16 23:46:31,Ford_Mondeo_2.0_Turnier_TDCi_DPF_Titanium,privat,Angebot,7500.0,test,kombi,2007,manuell,131,mondeo,150000.0,11,diesel,ford,nein,2016-03-16 00:00:00,0,34246,2016-04-05 16:21:16
37,2016-03-23 16:47:46,Seat_Altea_XL_2.0_TDI_CR_DPF_Style,privat,Angebot,13800.0,test,bus,2012,manuell,140,altea,90000.0,2,diesel,seat,nein,2016-03-23 00:00:00,0,85113,2016-04-05 20:17:53
38,2016-03-21 15:51:10,Volkswagen_Golf_1.4_Special,privat,Angebot,2850.0,control,limousine,2002,manuell,75,golf,125000.0,2,benzin,volkswagen,nein,2016-03-21 00:00:00,0,63674,2016-03-28 12:16:06
39,2016-03-11 13:58:38,Mercedes_C_180_Kombi__zu_verkaufen,privat,Angebot,1450.0,test,kombi,1999,automatik,122,c_klasse,150000.0,6,benzin,mercedes_benz,nein,2016-03-11 00:00:00,0,12683,2016-04-06 15:17:52
40,2016-03-07 14:50:03,VW_Golf__4_Cabrio_2.0_GTI_16V___Leder_MFA_Alus...,privat,Angebot,3500.0,control,cabrio,1999,manuell,150,golf,150000.0,1,benzin,volkswagen,nein,2016-03-07 00:00:00,0,6780,2016-03-12 02:15:52
41,2016-03-10 10:46:08,Passat_3b_1.9_TDI_Highline__angemeldet_mit_tuv...,privat,Angebot,3200.0,test,kombi,2003,manuell,131,NaN,150000.0,7,NaN,volkswagen,nein,2016-03-10 00:00:00,0,28259,2016-04-06 20:19:08
42,2016-03-22 21:37:03,Vw_Polo_l.0_/60_PS_Blue_Motion_Technologie_Son...,privat,Angebot,11900.0,control,kleinwagen,2014,manuell,60,polo,20000.0,7,benzin,volkswagen,NaN,2016-03-22 00:00:00,0,26629,2016-04-06 18:44:39
43,2016-03-08 16:51:22,Audi_A1_1.2_TFSI_Attraction_mit_Garantie,privat,Angebot,11500.0,test,kleinwagen,2011,manuell,86,a1,60000.0,9,benzin,audi,nein,2016-03-08 00:00:00,0,85049,2016-04-07 03:16:05
44,2016-03-12 10:38:06,Zu_verkaufen,privat,Angebot,900.0,control,kleinwagen,1998,manuell,43,twingo,150000.0,7,benzin,renault,nein,2016-03-12 00:00:00,0,79725,2016-04-06 01:17:27
45,2016-03-12 17:39:55,Toyota_Starlet_1.3,privat,Angebot,1000.0,test,kleinwagen,1995,manuell,75,andere,150000.0,3,benzin,toyota,nein,2016-03-12 00:00:00,0,74597,2016-04-07 08:45:19
46,2016-03-31 10:53:28,BMW_mit__Lpg,privat,Angebot,9000.0,control,NaN,2005,automatik,0,NaN,150000.0,0,NaN,bmw,NaN,2016-03-31 00:00:00,0,12351,2016-04-06 03:44:41
47,2016-03-28 19:51:51,Mercedes_Benz_A_150,privat,Angebot,3499.0,control,limousine,2008,manuell,95,a_klasse,150000.0,8,benzin,mercedes_benz,nein,2016-03-28 00:00:00,0,59557,2016-04-01 05:17:51
48,2016-03-20 12:41:50,Mercedes_C180_Sport_1_8l,privat,Angebot,1099.0,test,limousine,1998,manuell,122,c_klasse,150000.0,2,benzin,mercedes_benz,nein,2016-03-20 00:00:00,0,83024,2016-03-24 03:17:53
49,2016-03-27 15:36:42,Mercedes_Benz_CL_500__BlueEFFICIENCY__7G_TRONIC,privat,Angebot,56000.0,control,coupe,2012,automatik,435,cl,60000.0,2,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,34474,2016-04-05 11:47:52

In [338]:
# It can be observed that the values for 'seller' and 'offer_type' has almost identical entries in each.
# The 'nr_of_pictures' column has almost identical values
# All three columns can be dropped and would not make any impact to the data set.

In [339]:
autos.drop(["seller", 'offer_type', 'nr_of_pictures'], axis = 1)

,date_crawled,name,price_$,abtest,vehicle_type,registration_year,gearbox,power_p_s,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,5000.0,control,bus,2004,manuell,158,andere,150000.0,3,lpg,peugeot,nein,2016-03-26 00:00:00,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,8500.0,control,limousine,1997,automatik,286,7er,150000.0,6,benzin,bmw,nein,2016-04-04 00:00:00,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,8990.0,test,limousine,2009,manuell,102,golf,70000.0,7,benzin,volkswagen,nein,2016-03-26 00:00:00,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,4350.0,control,kleinwagen,2007,automatik,71,fortwo,70000.0,6,benzin,smart,nein,2016-03-12 00:00:00,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,1350.0,test,kombi,2003,manuell,0,focus,150000.0,7,benzin,ford,nein,2016-04-01 00:00:00,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,7900.0,test,bus,2006,automatik,150,voyager,150000.0,4,diesel,chrysler,NaN,2016-03-21 00:00:00,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,300.0,test,limousine,1995,manuell,90,golf,150000.0,8,benzin,volkswagen,NaN,2016-03-20 00:00:00,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,1990.0,control,limousine,1998,manuell,90,golf,150000.0,12,diesel,volkswagen,nein,2016-03-16 00:00:00,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,250.0,test,NaN,2000,manuell,0,arosa,150000.0,10,NaN,seat,nein,2016-03-22 00:00:00,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,590.0,control,bus,1997,manuell,90,megane,150000.0,7,benzin,renault,nein,2016-03-16 00:00:00,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,999.0,test,NaN,2017,manuell,90,NaN,150000.0,4,benzin,volkswagen,nein,2016-03-14 00:00:00,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,350.0,control,NaN,2000,NaN,0,NaN,150000.0,0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,5299.0,control,kleinwagen,2010,automatik,71,fortwo,50000.0,9,benzin,smart,nein,2016-03-31 00:00:00,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,1350.0,control,limousine,1999,manuell,101,a3,150000.0,11,benzin,audi,nein,2016-03-23 00:00:00,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,3999.0,test,kleinwagen,2007,manuell,75,clio,150000.0,9,benzin,renault,NaN,2016-03-23 00:00:00,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,18900.0,test,coupe,1982,automatik,203,NaN,80000.0,6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,350.0,test,kombi,1999,manuell,101,vectra,150000.0,5,benzin,opel,nein,2016-03-16 00:00:00,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,5500.0,test,coupe,1990,manuell,205,scirocco,150000.0,6,benzin,volkswagen,nein,2016-03-29 00:00:00,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,300.0,control,bus,1995,manuell,150,3er,150000.0,0,benzin,bmw,NaN,2016-03-26 00:00:00,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,4150.0,control,suv,2004,manuell,124,andere,150000.0,2,lpg,mazda,nein,2016-03-17 00:00:00,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,3500.0,test,kombi,2003,manuell,131,a4,150000.0,5,diesel,audi,NaN,2016-03-05 00:00:00,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,41500.0,test,cabrio,2004,manuell,320,911,150000.0,4,benzin,porsche,nein,2016-03-06 00:00:00,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,25450.0,control,cabrio,2015,manuell,184,cooper,10000.0,1,benzin,mini,nein,2016-03-28 00:00:00,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,7999.0,control,bus,2010,manuell,120,NaN,150000.0,2,diesel,peugeot,nein,2016-03-10 00:00:00,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,48500.0,control,limousine,2014,automatik,306,5er,30000.0,12,benzin,bmw,nein,2016-04-03 00:00:00,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,90.0,control,kombi,1996,manuell,116,NaN,150000.0,4,benzin,ford,ja,2016-03-21 00:00:00,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,777.0,control,kleinwagen,1992,manuell,54,polo,125000.0,2,benzin,volkswagen,nein,2016-04-03 00:00:00,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,0.0,control,NaN,2005,NaN,0,NaN,150000.0,0,NaN,ford,NaN,2016-03-27 00:00:00,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,5250.0,control,kleinwagen,2007,manuell,110,cooper,150000.0,7,diesel,mini,ja,2016-03-19 00:00:00,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,4999.0,test,kombi,2004,automatik,204,e_klasse,150000.0,10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,15800.0,control,bus,2010,automatik,136,c4,60000.0,4,diesel,citroen,nein,2016-03-21 00:00:00,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,950.0,test,kleinwagen,2001,manuell,50,lupo,150000.0,4,benzin,volkswagen,nein,2016-03-29 00:00:00,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,3300.0,control,bus,2004,automatik,150,vito,150000.0,10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,6000.0,control,cabrio,2004,manuell,163,slk,150000.0,11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,0.0,control,cabrio,1983,manuell,70,golf,150000.0,2,benzin,volkswagen,nein,2016-03-20 00:00:00,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,9700.0,control,kleinwagen,2012,automatik,88,jazz,100000.0,11,hybrid,honda,nein,2016-03-27 00:00:00,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,5900.0,test,kombi,1992,automatik,150,80,150000.0,12,benzin,audi,nein,2016-03-19 00:00:00,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,5500.0,control,limousine,2003,manuell,116,c_klasse,150000.0,2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,900.0,control,limousine,1996,automatik,136,e_klasse,150000.0,9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,11000.0,test,kleinwagen,2011,manuell,90,polo,70000.0,11,diesel,volkswagen,nein,2016-03-20 00:00:00,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,400.0,control,kombi,1995,manuell,105,escort,125000.0,3,benzin,ford,NaN,2016-03-12 00:00:00,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,2000.0,control,kombi,1998,manuell,115,astra,150000.0,12,benzin,opel,nein,2016-03-15 00:00:00,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,1950.0,control,kleinwagen,2004,manuell,0,fabia,90000.0,7,benzin,skoda,NaN,2016-03-29 00:00:00,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,600.0,test,kleinwagen,1999,manuell,101,focus,150000.0,4,benzin,ford,NaN,2016-03-06 00:00:00,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,0.0,test,NaN,2000,NaN,0,NaN,150000.0,0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,1000.0,control,NaN,1995,automatik,0,NaN,150000.0,0,benzin,volkswagen,NaN,2016-04-02 00:00:00,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,15900.0,control,limousine,2010,automatik,218,300c,125000.0,11,diesel,chrysler,nein,2016-04-04 00:00:00,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,21990.0,control,limousine,2013,manuell,150,a3,50000.0,11,diesel,audi,nein,2016-03-22 00:00:00,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,9550.0,control,coupe,2001,manuell,231,3er,150000.0,10,benzin,bmw,nein,2016-03-28 00:00:00,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,150.0,test,kleinwagen,1997,manuell,0,polo,150000.0,5,benzin,volkswagen,ja,2016-03-11 00:00:00,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,17500.0,test,limousine,2012,manuell,156,a_klasse,30000.0,12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,500.0,control,NaN,2016,manuell,0,twingo,150000.0,0,benzin,renault,NaN,2016-03-06 00:00:00,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,4800.0,control,kleinwagen,2009,manuell,120,andere,125000.0,9,lpg,fiat,nein,2016-03-10 00:00:00,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,1650.0,control,kleinwagen,1997,manuell,0,NaN,150000.0,7,benzin,audi,NaN,2016-03-15 00:00:00,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,5000.0,control,kombi,2001,automatik,299,a6,150000.0,1,benzin,audi,nein,2016-03-22 00:00:00,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,24900.0,control,limousine,2011,automatik,239,q5,100000.0,1,diesel,audi,nein,2016-03-27 00:00:00,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÜV_neu+...,1980.0,control,cabrio,1996,manuell,75,astra,150000.0,5,benzin,opel,nein,2016-03-28 00:00:00,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,13200.0,test,cabrio,2014,automatik,69,500,5000.0,11,benzin,fiat,nein,2016-04-02 00:00:00,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,22900.0,control,kombi,2013,manuell,150,a3,40000.0,11,diesel,audi,nein,2016-03-08 00:00:00,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,1250.0,control,limousine,1996,manuell,101,vectra,150000.0,1,benzin,opel,nein,2016-03-13 00:00:00,45897,2016-04-06 21:18:48

In [340]:
# Exploring the odometer_km and price_$ columns:

In [341]:
autos['odometer_km'].unique().shape

(13,)

In [342]:
autos['price_$'].unique().shape

(2357,)

In [343]:
autos['odometer_km'].describe()

count     50000.000000
mean     125732.700000
std       40042.211706
min        5000.000000
25%      125000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: odometer_km, dtype: float64

In [344]:
autos['price_$'].describe()

count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price_$, dtype: float64

In [345]:
# The above statistics shows the least price of the auction cars to be $0 and maximum to be over a million
# There is the need to set a ceiling for the cost of cars from $(1 to 350000)

In [346]:
autos['odometer_km'].value_counts().head(20)

150000.0    32424
125000.0     5170
100000.0     2169
90000.0      1757
80000.0      1436
70000.0      1230
60000.0      1164
50000.0      1027
5000.0        967
40000.0       819
30000.0       789
20000.0       784
10000.0       264
Name: odometer_km, dtype: int64

In [347]:
autos['price_$'].value_counts().head(20)

0.0       1421
500.0      781
1500.0     734
2500.0     643
1200.0     639
1000.0     639
600.0      531
800.0      498
3500.0     498
2000.0     460
999.0      434
750.0      433
900.0      420
650.0      419
850.0      410
700.0      395
4500.0     394
300.0      384
2200.0     382
950.0      379
Name: price_$, dtype: int64

In [348]:
# It appears that there are 1421 cars with $0 dollars price in value which can be removed

In [349]:
print(autos['odometer_km'].sort_index(ascending = True).head())
print()
print(autos['odometer_km'].sort_index(ascending = False).head())

0       150000.0
1       150000.0
10      150000.0
100      90000.0
1000    125000.0
Name: odometer_km, dtype: float64

9999    150000.0
9998    125000.0
9997    150000.0
9996    150000.0
9995    150000.0
Name: odometer_km, dtype: float64

In [350]:
print(autos['price_$'].sort_index(ascending = True).head())
print()
print(autos['price_$'].sort_index(ascending = False).head())

0       5000.0
1       8500.0
10       999.0
100     4500.0
1000    1000.0
Name: price_$, dtype: float64

9999    5750.0
9998     890.0
9997       0.0
9996    2000.0
9995    5200.0
Name: price_$, dtype: float64

In [351]:
# Removing price outliers from the autos dataset:

In [352]:
autos = autos[autos["price_$"].between(1, 351000)]
autos['price_$'].describe()

count     48565.000000
mean       5888.935591
std        9059.854754
min           1.000000
25%        1200.000000
50%        3000.000000
75%        7490.000000
max      350000.000000
Name: price_$, dtype: float64

In [353]:
autos['registration_month'].describe()

count    48565.000000
mean         5.782251
std          3.685595
min          0.000000
25%          3.000000
50%          6.000000
75%          9.000000
max         12.000000
Name: registration_month, dtype: float64

In [354]:
# It can be observed that registration month has a minimum value of '0' which is incorrect because there cannot be a zero month

In [355]:
# Exploring the columns : date_crawled, ad_created and last_seen

In [356]:
autos["date_crawled"].describe()

count                   48565
unique                  46882
top       2016-03-05 16:57:05
freq                        3
Name: date_crawled, dtype: object

In [357]:
autos["ad_created"].describe()

count                   48565
unique                     76
top       2016-04-03 00:00:00
freq                     1887
Name: ad_created, dtype: object

In [358]:
autos["last_seen"].describe()

count                   48565
unique                  38474
top       2016-04-07 06:17:27
freq                        8
Name: last_seen, dtype: object

In [359]:
# Observations:
## The data type for all above three columns are objects
## Column 'ad_created' has an abnormally higher frequency

In [360]:
autos["date_crawled"].value_counts(normalize=True, dropna=False)

2016-03-05 16:57:05    0.000062
2016-03-08 10:40:35    0.000062
2016-04-02 11:37:04    0.000062
2016-03-23 18:39:34    0.000062
2016-03-11 22:38:16    0.000062
2016-03-22 09:51:06    0.000062
2016-03-23 19:38:20    0.000062
2016-03-09 11:54:38    0.000062
2016-03-12 16:06:22    0.000062
2016-03-16 21:50:53    0.000062
2016-03-25 19:57:10    0.000062
2016-04-02 15:49:30    0.000062
2016-03-19 17:36:18    0.000062
2016-03-30 19:48:02    0.000062
2016-03-14 20:50:02    0.000062
2016-04-04 16:40:33    0.000062
2016-03-29 23:42:13    0.000062
2016-03-21 20:37:19    0.000062
2016-04-06 21:25:35    0.000041
2016-04-01 21:42:51    0.000041
2016-03-07 17:42:19    0.000041
2016-03-16 23:46:08    0.000041
2016-03-17 14:48:08    0.000041
2016-03-26 21:25:20    0.000041
2016-03-27 03:36:54    0.000041
2016-03-15 09:49:48    0.000041
2016-03-24 11:54:49    0.000041
2016-03-21 14:48:22    0.000041
2016-03-21 10:51:51    0.000041
2016-04-02 21:49:18    0.000041
                         ...
2016-04-05 11:51:12    0.000021
2016-03-12 17:45:23    0.000021
2016-03-10 11:52:09    0.000021
2016-03-13 17:38:00    0.000021
2016-03-23 17:38:40    0.000021
2016-03-08 20:43:39    0.000021
2016-03-07 22:40:36    0.000021
2016-03-19 09:49:22    0.000021
2016-03-22 08:56:44    0.000021
2016-03-26 11:50:09    0.000021
2016-04-04 13:46:26    0.000021
2016-03-24 02:36:35    0.000021
2016-03-12 13:57:36    0.000021
2016-03-25 15:59:30    0.000021
2016-03-29 14:58:39    0.000021
2016-03-27 17:52:45    0.000021
2016-03-11 00:58:08    0.000021
2016-03-10 15:36:41    0.000021
2016-03-20 21:55:34    0.000021
2016-03-31 13:51:05    0.000021
2016-03-29 18:49:24    0.000021
2016-04-05 10:52:08    0.000021
2016-03-21 15:50:28    0.000021
2016-03-25 22:51:08    0.000021
2016-03-16 14:39:18    0.000021
2016-03-21 18:37:58    0.000021
2016-03-08 14:49:04    0.000021
2016-03-20 12:42:33    0.000021
2016-03-09 17:55:49    0.000021
2016-03-25 18:52:19    0.000021
Name: date_crawled, Length: 46882, dtype: float64

In [361]:
autos["ad_created"].value_counts(normalize=True, dropna=False)

2016-04-03 00:00:00    0.038855
2016-03-20 00:00:00    0.037949
2016-03-21 00:00:00    0.037579
2016-04-04 00:00:00    0.036858
2016-03-12 00:00:00    0.036755
2016-03-14 00:00:00    0.035190
2016-04-02 00:00:00    0.035149
2016-03-28 00:00:00    0.034984
2016-03-07 00:00:00    0.034737
2016-03-29 00:00:00    0.034037
2016-03-15 00:00:00    0.034016
2016-04-01 00:00:00    0.033687
2016-03-19 00:00:00    0.033687
2016-03-30 00:00:00    0.033501
2016-03-08 00:00:00    0.033316
2016-03-09 00:00:00    0.033151
2016-03-11 00:00:00    0.032904
2016-03-22 00:00:00    0.032801
2016-03-26 00:00:00    0.032266
2016-03-23 00:00:00    0.032060
2016-03-10 00:00:00    0.031895
2016-03-31 00:00:00    0.031875
2016-03-25 00:00:00    0.031751
2016-03-17 00:00:00    0.031278
2016-03-27 00:00:00    0.030989
2016-03-16 00:00:00    0.030125
2016-03-24 00:00:00    0.029280
2016-03-05 00:00:00    0.022897
2016-03-13 00:00:00    0.017008
2016-03-06 00:00:00    0.015320
                         ...
2016-02-24 00:00:00    0.000041
2016-02-14 00:00:00    0.000041
2016-02-12 00:00:00    0.000041
2016-02-18 00:00:00    0.000041
2016-02-05 00:00:00    0.000041
2016-02-20 00:00:00    0.000041
2016-02-02 00:00:00    0.000041
2016-02-26 00:00:00    0.000041
2016-01-10 00:00:00    0.000041
2016-01-14 00:00:00    0.000021
2015-11-10 00:00:00    0.000021
2016-01-16 00:00:00    0.000021
2016-02-07 00:00:00    0.000021
2016-02-17 00:00:00    0.000021
2016-01-03 00:00:00    0.000021
2016-02-08 00:00:00    0.000021
2015-12-05 00:00:00    0.000021
2016-02-16 00:00:00    0.000021
2016-02-09 00:00:00    0.000021
2016-01-22 00:00:00    0.000021
2016-02-22 00:00:00    0.000021
2015-12-30 00:00:00    0.000021
2015-09-09 00:00:00    0.000021
2016-01-07 00:00:00    0.000021
2016-01-13 00:00:00    0.000021
2016-02-11 00:00:00    0.000021
2015-08-10 00:00:00    0.000021
2016-02-01 00:00:00    0.000021
2015-06-11 00:00:00    0.000021
2016-01-29 00:00:00    0.000021
Name: ad_created, Length: 76, dtype: float64

In [362]:
autos["last_seen"].value_counts(normalize=True, dropna=False)

2016-04-07 06:17:27    0.000165
2016-04-07 03:16:17    0.000144
2016-04-06 21:17:51    0.000144
2016-04-06 06:17:24    0.000124
2016-04-06 08:44:19    0.000124
2016-04-06 02:17:26    0.000124
2016-04-06 15:16:45    0.000124
2016-04-06 07:46:11    0.000124
2016-04-06 10:17:12    0.000124
2016-04-06 22:17:26    0.000124
2016-04-06 19:16:38    0.000124
2016-04-06 15:45:50    0.000124
2016-04-06 13:17:03    0.000124
2016-04-07 04:46:51    0.000124
2016-04-07 03:45:23    0.000124
2016-04-05 16:44:47    0.000124
2016-04-07 06:46:12    0.000124
2016-04-06 14:44:55    0.000124
2016-04-06 15:17:56    0.000124
2016-04-07 05:16:17    0.000124
2016-04-06 20:48:27    0.000124
2016-04-06 02:16:12    0.000124
2016-04-06 05:16:14    0.000124
2016-04-06 14:17:04    0.000124
2016-04-07 06:17:09    0.000103
2016-04-06 09:45:36    0.000103
2016-04-06 06:17:01    0.000103
2016-04-07 05:16:23    0.000103
2016-04-07 02:45:44    0.000103
2016-04-07 07:44:37    0.000103
                         ...
2016-03-08 16:43:50    0.000021
2016-03-25 23:15:40    0.000021
2016-04-06 18:17:42    0.000021
2016-03-28 17:39:26    0.000021
2016-03-20 04:19:39    0.000021
2016-03-27 17:38:20    0.000021
2016-04-02 08:36:16    0.000021
2016-03-20 06:44:42    0.000021
2016-03-12 07:45:49    0.000021
2016-04-02 11:17:22    0.000021
2016-04-07 03:16:51    0.000021
2016-03-28 22:46:59    0.000021
2016-04-06 22:46:02    0.000021
2016-03-26 12:51:33    0.000021
2016-04-01 03:46:40    0.000021
2016-03-29 15:27:28    0.000021
2016-04-04 07:45:18    0.000021
2016-03-21 17:46:26    0.000021
2016-03-12 14:17:19    0.000021
2016-03-29 22:15:40    0.000021
2016-03-15 14:45:41    0.000021
2016-04-05 16:46:40    0.000021
2016-04-04 22:18:15    0.000021
2016-03-14 10:46:22    0.000021
2016-03-26 17:16:13    0.000021
2016-04-02 16:17:14    0.000021
2016-04-07 11:17:15    0.000021
2016-04-03 14:45:33    0.000021
2016-04-06 22:47:10    0.000021
2016-04-06 16:44:52    0.000021
Name: last_seen, Length: 38474, dtype: float64

In [363]:
autos["date_crawled"].sort_index(ascending=True)

0        2016-03-26 17:47:46
1        2016-04-04 13:38:56
10       2016-03-15 01:41:36
100      2016-03-12 18:57:48
1000     2016-03-14 17:06:20
10000    2016-04-02 10:40:22
10001    2016-03-14 21:25:25
10002    2016-04-03 23:47:43
10003    2016-03-28 21:46:23
10004    2016-03-26 19:51:26
10005    2016-03-05 17:48:24
10006    2016-03-30 16:52:44
10007    2016-03-30 10:37:17
10008    2016-03-15 16:51:36
10009    2016-03-06 21:49:27
1001     2016-04-01 23:50:04
10010    2016-03-07 18:40:16
10011    2016-03-07 17:52:38
10012    2016-03-19 10:48:39
10013    2016-03-28 23:40:08
10014    2016-03-30 11:51:56
10015    2016-03-15 11:51:03
10016    2016-03-21 19:43:55
10017    2016-04-02 09:45:06
10018    2016-04-02 13:56:35
10019    2016-03-15 00:52:25
1002     2016-03-29 18:51:37
10020    2016-03-24 16:55:26
10021    2016-04-05 07:58:32
10022    2016-04-01 14:36:51
                ...
9971     2016-03-12 17:49:25
9972     2016-03-21 17:45:28
9973     2016-03-16 13:52:49
9974     2016-03-28 13:44:11
9975     2016-03-16 09:37:21
9976     2016-03-31 14:45:26
9977     2016-03-17 16:52:41
9978     2016-03-22 16:55:47
9979     2016-03-31 19:55:35
998      2016-04-02 16:51:49
9980     2016-03-31 14:55:36
9981     2016-04-03 13:46:51
9982     2016-03-06 01:36:42
9983     2016-03-29 12:46:43
9984     2016-03-16 12:50:31
9985     2016-03-05 21:52:54
9986     2016-04-01 01:58:55
9987     2016-03-28 12:44:08
9988     2016-03-15 18:44:23
9989     2016-04-01 12:50:19
999      2016-03-29 10:54:15
9990     2016-03-28 12:52:57
9991     2016-04-03 12:48:39
9992     2016-04-02 23:45:45
9993     2016-03-10 17:54:56
9994     2016-03-31 20:55:17
9995     2016-03-11 20:55:51
9996     2016-03-05 20:57:12
9998     2016-03-23 22:51:12
9999     2016-03-10 02:36:58
Name: date_crawled, Length: 48565, dtype: object

In [364]:
autos["ad_created"].sort_index(ascending=True)

0        2016-03-26 00:00:00
1        2016-04-04 00:00:00
10       2016-03-14 00:00:00
100      2016-03-12 00:00:00
1000     2016-03-14 00:00:00
10000    2016-04-02 00:00:00
10001    2016-03-14 00:00:00
10002    2016-04-03 00:00:00
10003    2016-03-28 00:00:00
10004    2016-03-26 00:00:00
10005    2016-03-05 00:00:00
10006    2016-03-30 00:00:00
10007    2016-03-30 00:00:00
10008    2016-03-15 00:00:00
10009    2016-03-06 00:00:00
1001     2016-04-01 00:00:00
10010    2016-03-07 00:00:00
10011    2016-03-07 00:00:00
10012    2016-03-19 00:00:00
10013    2016-03-28 00:00:00
10014    2016-03-30 00:00:00
10015    2016-03-15 00:00:00
10016    2016-03-21 00:00:00
10017    2016-04-02 00:00:00
10018    2016-04-02 00:00:00
10019    2016-03-14 00:00:00
1002     2016-03-29 00:00:00
10020    2016-03-24 00:00:00
10021    2016-04-05 00:00:00
10022    2016-04-01 00:00:00
                ...
9971     2016-03-12 00:00:00
9972     2016-03-21 00:00:00
9973     2016-03-16 00:00:00
9974     2016-03-28 00:00:00
9975     2016-03-16 00:00:00
9976     2016-03-31 00:00:00
9977     2016-03-17 00:00:00
9978     2016-03-22 00:00:00
9979     2016-03-31 00:00:00
998      2016-04-02 00:00:00
9980     2016-03-31 00:00:00
9981     2016-04-03 00:00:00
9982     2016-03-06 00:00:00
9983     2016-03-29 00:00:00
9984     2016-03-16 00:00:00
9985     2016-03-05 00:00:00
9986     2016-04-01 00:00:00
9987     2016-03-28 00:00:00
9988     2016-03-15 00:00:00
9989     2016-04-01 00:00:00
999      2016-03-29 00:00:00
9990     2016-03-28 00:00:00
9991     2016-04-03 00:00:00
9992     2016-04-02 00:00:00
9993     2016-03-10 00:00:00
9994     2016-03-31 00:00:00
9995     2016-03-11 00:00:00
9996     2016-03-05 00:00:00
9998     2016-03-23 00:00:00
9999     2016-03-10 00:00:00
Name: ad_created, Length: 48565, dtype: object

In [365]:
autos["last_seen"].sort_index(ascending=True)

0        2016-04-06 06:45:54
1        2016-04-06 14:45:08
10       2016-04-07 03:16:21
100      2016-04-07 12:47:06
1000     2016-03-25 08:17:50
10000    2016-04-06 08:15:32
10001    2016-03-28 17:45:14
10002    2016-04-06 06:16:45
10003    2016-03-30 13:46:54
10004    2016-03-26 19:51:26
10005    2016-03-08 19:21:38
10006    2016-04-07 08:16:44
10007    2016-03-30 10:37:17
10008    2016-03-15 16:51:36
10009    2016-03-09 08:47:06
1001     2016-04-06 01:45:27
10010    2016-03-09 15:49:05
10011    2016-04-06 19:46:32
10012    2016-04-06 11:16:43
10013    2016-03-30 15:45:21
10014    2016-03-30 11:51:56
10015    2016-04-05 23:18:18
10016    2016-04-06 21:47:29
10017    2016-04-02 09:45:06
10018    2016-04-06 12:16:40
10019    2016-04-05 13:17:02
1002     2016-04-06 04:45:50
10020    2016-04-07 09:17:31
10021    2016-04-05 07:58:32
10022    2016-04-07 06:16:56
                ...
9971     2016-04-07 09:46:04
9972     2016-04-06 17:46:56
9973     2016-03-17 11:46:02
9974     2016-04-06 16:46:48
9975     2016-04-06 02:17:51
9976     2016-03-31 14:45:26
9977     2016-03-30 11:46:14
9978     2016-03-29 21:46:55
9979     2016-04-06 14:18:08
998      2016-04-04 14:46:05
9980     2016-04-06 08:16:51
9981     2016-04-03 13:46:51
9982     2016-04-06 01:17:03
9983     2016-04-03 21:15:27
9984     2016-03-21 13:16:11
9985     2016-03-17 22:44:42
9986     2016-04-01 08:43:45
9987     2016-03-31 20:44:24
9988     2016-03-22 23:15:33
9989     2016-04-07 09:17:51
999      2016-04-03 19:45:59
9990     2016-04-06 16:15:25
9991     2016-04-07 14:58:25
9992     2016-04-07 00:46:08
9993     2016-04-05 19:45:55
9994     2016-04-04 14:45:14
9995     2016-03-22 16:18:18
9996     2016-03-17 00:18:17
9998     2016-04-07 02:45:54
9999     2016-04-02 04:44:33
Name: last_seen, Length: 48565, dtype: object

In [366]:
autos["registration_year"].describe()

count    48565.000000
mean      2004.755421
std         88.643887
min       1000.000000
25%       1999.000000
50%       2004.000000
75%       2008.000000
max       9999.000000
Name: registration_year, dtype: float64

In [367]:
# minimum year of 10000 and maximum year of 9999 is very unlikely for the data above

In [368]:
# Dealing with the registration year problem
## The maximum year should never be 2016(listing_year) and neither should it be before the year 1900

In [369]:
autos = autos[autos["registration_year"].between(1900, 2016)]
autos["registration_year"].value_counts(normalize=True).head(15)

2000    0.067608
2005    0.062895
1999    0.062060
2004    0.057904
2003    0.057818
2006    0.057197
2001    0.056468
2002    0.053255
1998    0.050620
2007    0.048778
2008    0.047450
2009    0.044665
1997    0.041794
2011    0.034768
2010    0.034040
Name: registration_year, dtype: float64

In [370]:
# Column has been put in a reasonable range

In [371]:
# Using aggregation to explore the 'brand' column

In [372]:
autos["brand"].describe()

count          46681
unique            40
top       volkswagen
freq            9862
Name: brand, dtype: object

In [373]:
autos["brand"].value_counts(normalize = True).head(20)

volkswagen        0.211264
bmw               0.110045
opel              0.107581
mercedes_benz     0.096463
audi              0.086566
ford              0.069900
renault           0.047150
peugeot           0.029841
fiat              0.025642
seat              0.018273
skoda             0.016409
nissan            0.015274
mazda             0.015188
smart             0.014160
citroen           0.014010
toyota            0.012703
hyundai           0.010025
sonstige_autos    0.009811
volvo             0.009147
mini              0.008762
Name: brand, dtype: float64

In [374]:
# German manufacturers are amongst the top with volkswagen leading

In [375]:
autos["brand"].index

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '49990', '49991', '49992', '49993', '49994', '49995', '49996', '49997',
       '49998', '49999'],
      dtype='object', length=46681)

In [376]:
# We will base our analysis on atleast 5% of the brand names in the data

In [377]:
selection = autos["brand"].value_counts(normalize=True)
brand_select = selection[selection > 0.05].index
brand_select

Index(['volkswagen', 'bmw', 'opel', 'mercedes_benz', 'audi', 'ford'], dtype='object')

In [378]:
# The above brands falls within the greater than 5% values.

In [379]:
aggregate_data = dict()

for brand in brand_select:
    match_brand = autos[autos["brand"] == brand]
    brand_price = match_brand["price_$"].mean()
    aggregate_data[brand] = int(brand_price)
brand_mean_prices = aggregate_data
brand_mean_prices

{'audi': 9336,
 'bmw': 8332,
 'ford': 3749,
 'mercedes_benz': 8628,
 'opel': 2975,
 'volkswagen': 5402}

In [380]:
# The data above indicates 'audi' as the manufacturer with the greatest mean and 'opel' with the least.
## This indicates how expensive audi cars can be with opel and ford being the least expensive and the rest fall inbetween.

In [381]:
# Calculating the mean_mileage

In [382]:
brand_mean_mileage = {}

for brand in brand_select:
    match_brand = autos[autos["brand"] == brand]
    brand_mileage = match_brand["odometer_km"].mean()
    brand_mean_mileage[brand] = int(brand_mileage)
brand_mean_mileage


mean_prices = pd.Series(brand_mean_prices).sort_values(ascending = False)
mean_mileage = pd.Series(brand_mean_mileage).sort_values(ascending = False)

In [ ]:
# Both prices and mileages need to be sorted out to align the data or get them working in the same dataframe
# panda methods pd.DataFrame and pd.Series are use to create both series objects and dataframe objects respectively

In [383]:
bmp_series = pd.Series(mean_prices)
pd.DataFrame(bmp_series, columns=['mean_price'])

               mean_price
audi                 9336
mercedes_benz        8628
bmw                  8332
volkswagen           5402
ford                 3749
opel                 2975

In [384]:
bmm = pd.Series(mean_mileage)
pd.DataFrame(bmm, columns = ["mean_mileage"])

               mean_mileage
bmw                  132572
mercedes_benz        130788
opel                 129310
audi                 129157
volkswagen           128707
ford                 124266

In [ ]:
# Grouping both mean_mileage and mean_price using the pandas 'pd.Dataframe' method to first assign to a variable and add the column to the frame

In [385]:
new_df = pd.DataFrame(mean_mileage, columns = ["mean_mileage"])
new_df["mean_price"] = mean_prices
new_df

               mean_mileage  mean_price
bmw                  132572        8332
mercedes_benz        130788        8628
opel                 129310        2975
audi                 129157        9336
volkswagen           128707        5402
ford                 124266        3749

In [ ]:
# There is an obvious correlation between expensive cars and mileage. Since these cars are expensive, they are driven or used most often than other vehicles.
# BMW and Mercedes_benz tops the chart with price and mileages with Ford and Volkswa